import MapDetailPage from "@/components/Pages/MapDetail/MapDetailPage";
import { Suspense } from "react";

export const metadata = {
  title: "Map | JumpersHeaven",
  description: "Generated by create next app",
};

async function MapPage() {
  return (
    <Suspense fallback={<div>Loading...</div>}>
      <MapDetailPage />
    </Suspense>
  );
}

export default MapPage;
