import MapsPage from "@/Components/Pages/Maps/MapsPage/MapsPage";

export const metadata = {
  title: "Maps | JumpersHeaven",
  description: "Generated by create next app",
};

const CoreMapsPage = () => {
  return <MapsPage />;
};

export default CoreMapsPage;
