import ScoringSystem from "@/components/Pages/ScoringSystem/ScoringSystem";

export const metadata = {
  title: "Scoring | JumpersHeaven",
  description: "Generated by create next app",
};

export default function ScoringPage() {
  return <ScoringSystem />;
}
