import FiltersSection from "@/components/Pages/Leaderboards/FiltersSection/FiltersSection";
import LeaderBoard from "@/components/Pages/Leaderboards/LeaderBoard/LeaderBoard";
import PlayerToolTip from "@/components/Pages/ServersPage/PlayerToolTip/PlayerToolTip";
import { Suspense } from "react";

export const metadata = {
  title: "Leaderboards | JumpersHeaven",
  description: "Generated by create next app",
};

const LeaderboardsPage = () => {
  return (
    <div className="container">
      <main>
        <Suspense fallback={<div>Loading...</div>}>
          <FiltersSection />
          <LeaderBoard />
        </Suspense>
        <PlayerToolTip />
      </main>
    </div>
  );
};

export default LeaderboardsPage;
