import FiltersSection from "@/Components/Pages/Leaderboards/FiltersSection/FiltersSection";
import LeaderBoard from "@/Components/Pages/Leaderboards/LeaderBoard/LeaderBoard";
import PageHeader from "@/Components/Shared/PageHeroSection/PageHeroSection";
import { Suspense } from "react";

export const metadata = {
  title: "Leaderboards | JumpersHeaven",
  description: "Generated by create next app",
};

const LeaderboardsPage = () => {
  return (
    <div className="container">
      <main>
        <PageHeader
          title="Leaderboard Rankings"
          description="Track and compare player statistics, achievements, and rankings across the community. See where you stand among the best players."
        />

        <Suspense fallback={<div>Loading...</div>}>
          <FiltersSection />
          <LeaderBoard />
        </Suspense>
      </main>
    </div>
  );
};

export default LeaderboardsPage;
