import About from "@/components/Pages/About/About";

export const metadata = {
  title: "About | JumpersHeaven",
  description: "Generated by create next app",
};

const AboutPage = () => {
  return <About />;
};

export default AboutPage;
