import MapDetailPage from "@/components/Pages/MapDetail/MapDetailPage";
import s from "@/components/Pages/MapDetail/MapPage.module.scss";
import Link from "next/link";
import { Suspense } from "react";

export const metadata = {
  title: "Map | JumpersHeaven",
  description: "Generated by create next app",
};

async function MapPage({ searchParams }) {
  const { mapid } = await searchParams;
  const mapIdExist = mapid !== undefined;

  return (
    <>
      {!mapIdExist && (
        <main>
          <div className="container">
            <section className={s.heroSection}>
              <h1>Maps Overview</h1>
              <p>
                Explore all jumpers heaven <Link href="/maps">maps</Link>. Click
                on a map to see detailed statistics and information.
              </p>
            </section>
          </div>
        </main>
      )}

      {mapIdExist && (
        <Suspense fallback={<div>Loading...</div>}>
          <MapDetailPage />
        </Suspense>
      )}
    </>
  );
}

export default MapPage;
