import PlayerOverview from "@/components/Pages/PlayerProfile/PlayerOverview/PlayerOverview";
import { Suspense } from "react";

export const metadata = {
  title: "Player | JumpersHeaven",
  description: "Generated by create next app",
};

const PlayerPage = () => {
  return (
    <Suspense fallback={<div>Loading...</div>}>
      <PlayerOverview />
    </Suspense>
  );
};

export default PlayerPage;
