import PlayerProfile from "@/Components/Pages/PlayerProfile/PlayerProfile";
import { Suspense } from "react";

export const metadata = {
  title: "Player | JumpersHeaven",
  description: "Generated by create next app",
};

const PlayerPage = () => {
  return (
    <Suspense fallback={<div>Loading...</div>}>
      <PlayerProfile />
    </Suspense>
  );
};

export default PlayerPage;
