export const metadata = {
  title: "Favorites | JumpersHeaven",
  description: "Generated by create next app",
};

const FavoritesPage = () => {
  return <main>FavoritesPage</main>;
};

export default FavoritesPage;
