import FavoritesSection from "@/components/Pages/Favorites/FavoritesSection/FavoritesSection";
import { Suspense } from "react";

export const metadata = {
  title: "Favorites | JumpersHeaven",
  description: "Generated by create next app",
};

const FavoritesPage = () => {
  return (
    <Suspense fallback={<div>Loading...</div>}>
      <FavoritesSection />
    </Suspense>
  );
};

export default FavoritesPage;
