import { jhApis } from "@/Api/jumpersHeaven";
import MapDetailPage from "@/Components/Pages/MapDetail/MapDetailPage";
import { decodeAsyncData, fetchMsgPackResponse } from "@/Functions/utils";

export async function generateMetadata({ params }) {
  const { cpid } = await params;

  try {
    const response = await fetchMsgPackResponse({
      url: jhApis().map.getAllMaps,
      cache: "no-cache",
    });
    const data = await decodeAsyncData(response);
    const map = data.find((map) => map.CpID === +cpid);

    return {
      title: map?.Name
        ? `${map.Name} | JumpersHeaven`
        : `Map ID ${cpid} | JumpersHeaven`,
      description: "Generated by create next app",
    };
  } catch (error) {
    return {
      title: `Map | JumpersHeaven`,
      description: "Explore detailed map information on JumpersHeaven.",
    };
  }
}

async function MapPage({ params }) {
  const { cpid } = await params;
  return <MapDetailPage cpid={cpid} />;
}

export default MapPage;
