import PlayerOverview from "@/components/Pages/PlayerProfile/PlayerOverview/PlayerOverview";

export const metadata = {
  title: "Player | JumpersHeaven",
  description: "Generated by create next app",
};

async function PlayerPage() {
  return <PlayerOverview />;
}

export default PlayerPage;
