import PlayersPage from "@/components/Pages/PlayersPage/PlayersPage";
import PlayerToolTip from "@/components/Pages/ServersPage/PlayerToolTip/PlayerToolTip";
import { Suspense } from "react";

export const metadata = {
  title: "Players | JumpersHeaven",
  description: "Generated by create next app",
};

const Page = () => {
  return (
    <div className="container">
      <main>
        <Suspense>
          <PlayersPage />
        </Suspense>
        <PlayerToolTip />
      </main>
    </div>
  );
};

export default Page;
