import PlayersPage from "@/Components/Pages/PlayersPage/PlayersPage";
import PlayerToolTip from "@/Components/Pages/ServersPage/PlayerToolTip/PlayerToolTip";

export const metadata = {
  title: "Players | JumpersHeaven",
  description: "Generated by create next app",
};

const Page = () => {
  return (
    <div className="container">
      <main>
        <PlayersPage />
        <PlayerToolTip />
      </main>
    </div>
  );
};

export default Page;
